spring:
  application:
    name: platzi-play
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
langchain4j:
  open-ai:
    chat-model:
      api-key: demo
      model-name: gpt-4o-mini
server:
  servlet:
    context-path: /api